-- =============================================================
-- SMA Bina Taruna — CMS schema (PostgreSQL / Supabase)
-- Dikonversi 1:1 dari versi MySQL: nama tabel, kolom, foreign key,
-- index, dan constraint tidak berubah — hanya sintaks & tipe yang
-- menyesuaikan PostgreSQL. Ringkasan pemetaan:
--   AUTO_INCREMENT              -> GENERATED BY DEFAULT AS IDENTITY
--   ENUM(...)                   -> CREATE TYPE ... AS ENUM (nilai & urutan sama)
--   TIMESTAMP                   -> TIMESTAMPTZ
--   ON UPDATE CURRENT_TIMESTAMP -> trigger set_updated_at()
--   TINYINT UNSIGNED / TINYINT(1) -> SMALLINT (+ CHECK), tetap angka 0/1
--   JSON                        -> JSONB
--   INDEX (...) di CREATE TABLE -> CREATE INDEX IF NOT EXISTS
--   blok information_schema + PREPARE/EXECUTE -> ADD COLUMN IF NOT EXISTS / blok DO
-- Every table that backs an editable list carries a `sort_order`
-- column so the admin dashboard can control display order with
-- simple move-up/move-down actions instead of drag-and-drop.
-- =============================================================

-- ---------------------------------------------------------------
-- Tipe ENUM. PostgreSQL tidak punya ENUM per-kolom seperti MySQL,
-- jadi tiap ENUM menjadi tipe bernama. Nilai & URUTAN persis sama
-- dengan versi MySQL — urutan penting karena ORDER BY pada kolom
-- ENUM mengurutkan menurut urutan deklarasi (mis. doc_type dibaca
-- kk, akta, ijazah, foto), sama seperti di MySQL. CREATE TYPE tidak
-- punya IF NOT EXISTS, jadi dibungkus agar aman dijalankan ulang.
-- ---------------------------------------------------------------
DO $$
BEGIN
  CREATE TYPE user_status AS ENUM ('pending_admin_approval', 'pending_verification', 'verified');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE ppdb_registration_status AS ENUM
    ('diajukan', 'perlu_revisi', 'diverifikasi', 'terkirim_ke_dinas', 'diterima', 'ditolak');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE ppdb_gender AS ENUM ('L', 'P');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE ppdb_doc_type AS ENUM ('kk', 'akta', 'ijazah', 'foto');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ---------------------------------------------------------------
-- Pengganti "ON UPDATE CURRENT_TIMESTAMP" MySQL. Perilakunya sama:
-- updated_at diperbarui hanya bila nilai kolom lain benar-benar
-- berubah, dan nilai yang diisi eksplisit oleh UPDATE tidak ditimpa.
-- SET search_path = '' mencegah peringatan "function search path
-- mutable" di Security Advisor Supabase (now() ada di pg_catalog).
-- ---------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  IF NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at AND NEW IS DISTINCT FROM OLD THEN
    NEW.updated_at := now();
  END IF;
  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------
-- Admin accounts (dashboard login)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admins (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(120)  NOT NULL,
  email         VARCHAR(190)  NOT NULL UNIQUE,
  password_hash VARCHAR(200)  NOT NULL,
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_admins_set_updated_at ON admins;
CREATE TRIGGER trg_admins_set_updated_at
  BEFORE UPDATE ON admins FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Akun pengguna publik (calon siswa/orang tua) — dipakai untuk login
-- sebelum mengisi formulir PPDB. Berbeda dari `admins` (dashboard).
--
-- Alur status:
--   pending_admin_approval  → baru daftar, menunggu admin menyetujui
--                             pengiriman kode verifikasi (lihat kolom
--                             verification_code_*). User BELUM bisa login.
--   pending_verification    → admin sudah menyetujui & kode terkirim
--                             lewat email (Nodemailer). User memasukkan
--                             kode ini untuk mengaktifkan akun.
--   verified                → email terverifikasi, user bisa login &
--                             mengisi formulir PPDB.
--
-- `verification_code_hash` menyimpan HASH (bukan kode polos) dari kode
-- 6-digit yang dikirim ke email — sama seperti password, supaya
-- kebocoran database tidak langsung membocorkan kode aktif siapa pun.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id                        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                      VARCHAR(120)  NOT NULL,
  email                     VARCHAR(190)  NOT NULL UNIQUE,
  password_hash             VARCHAR(200)  NOT NULL,
  status                    user_status   NOT NULL DEFAULT 'pending_admin_approval',

  verification_code_hash    VARCHAR(200)  NULL,
  verification_code_expires TIMESTAMPTZ   NULL,

  approved_by               INT           NULL,
  approved_at               TIMESTAMPTZ   NULL,
  verified_at               TIMESTAMPTZ   NULL,

  created_at                TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_users_approved_by FOREIGN KEY (approved_by) REFERENCES admins(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);

DROP TRIGGER IF EXISTS trg_users_set_updated_at ON users;
CREATE TRIGGER trg_users_set_updated_at
  BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Singleton: sekolahProfile (identitas & kontak sekolah)
-- Always exactly one row, id = 1.
-- (TINYINT UNSIGNED MySQL -> SMALLINT: PostgreSQL tidak punya tipe
-- unsigned/1-byte; CHECK (id = 1) tetap menjaga pola singleton.)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS school_profile (
  id               SMALLINT PRIMARY KEY DEFAULT 1,
  name             VARCHAR(150) NOT NULL,
  short_name       VARCHAR(150) NOT NULL,
  full_legal_name  VARCHAR(200) NOT NULL,
  tagline          VARCHAR(200) NOT NULL,
  motto            VARCHAR(400) NOT NULL,
  founded_year     SMALLINT     NOT NULL,
  accreditation    VARCHAR(50)  NOT NULL,
  npsn             VARCHAR(30)  NOT NULL,
  email            VARCHAR(190) NOT NULL,
  phone            VARCHAR(50)  NOT NULL,
  whatsapp         VARCHAR(50)  NOT NULL,
  address_street   VARCHAR(200) NOT NULL,
  address_area     VARCHAR(200) NOT NULL,
  address_city     VARCHAR(200) NOT NULL,
  instagram        VARCHAR(100) NULL,
  youtube          VARCHAR(150) NULL,
  facebook         VARCHAR(150) NULL,
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_school_profile_singleton CHECK (id = 1)
);

DROP TRIGGER IF EXISTS trg_school_profile_set_updated_at ON school_profile;
CREATE TRIGGER trg_school_profile_set_updated_at
  BEFORE UPDATE ON school_profile FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Statistik (Stats strip below hero)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stats (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon        VARCHAR(60)  NOT NULL,
  label       VARCHAR(150) NOT NULL,
  value       INT          NOT NULL,
  suffix      VARCHAR(10)  NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Sejarah — paragraf naratif
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS history_paragraphs (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content     TEXT         NOT NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Sejarah — tonggak sejarah / milestones (garis waktu)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS milestones (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year         VARCHAR(16)  NOT NULL,
  title        VARCHAR(200) NOT NULL,
  description  TEXT         NOT NULL,
  sort_order   INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Singleton: pernyataan visi. Misi disimpan terpisah (list).
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vision_mission (
  id          SMALLINT PRIMARY KEY DEFAULT 1,
  vision      TEXT        NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_vision_mission_singleton CHECK (id = 1)
);

DROP TRIGGER IF EXISTS trg_vision_mission_set_updated_at ON vision_mission;
CREATE TRIGGER trg_vision_mission_set_updated_at
  BEFORE UPDATE ON vision_mission FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS missions (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content     TEXT NOT NULL,
  sort_order  INT  NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Fasilitas
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS facilities (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon         VARCHAR(60)  NOT NULL,
  title        VARCHAR(200) NOT NULL,
  description  TEXT         NOT NULL,
  sort_order   INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Ekstrakurikuler
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS extracurriculars (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  icon        VARCHAR(60)  NOT NULL,
  name        VARCHAR(150) NOT NULL,
  -- Deskripsi detail yang tampil saat kartu ekskul diklik di halaman
  -- publik. NULL/kosong berarti belum diisi admin.
  description TEXT         NULL,
  -- Path publik relatif ke foto ekskul (mis. /uploads/photos/xxx.jpg),
  -- diisi lewat unggahan admin. NULL/kosong berarti belum ada foto.
  image_url   VARCHAR(255) NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Prestasi siswa
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS achievements (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name  VARCHAR(150) NOT NULL,
  grade         VARCHAR(100) NOT NULL,
  title         VARCHAR(200) NOT NULL,
  level         VARCHAR(150) NOT NULL,
  icon          VARCHAR(60)  NOT NULL,
  -- Path publik relatif ke foto siswa (mis. /uploads/photos/xxx.jpg),
  -- diisi lewat unggahan admin. NULL/kosong berarti belum ada foto —
  -- tampilan publik jatuh kembali ke ikon di atas.
  photo_url     VARCHAR(255) NULL,
  sort_order    INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Pimpinan sekolah
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS leadership (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  role        VARCHAR(150) NOT NULL,
  -- Path publik relatif ke foto pimpinan (mis. /uploads/photos/xxx.jpg),
  -- diisi lewat unggahan admin. NULL/kosong berarti belum ada foto —
  -- tampilan publik jatuh kembali ke avatar inisial.
  photo_url   VARCHAR(255) NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Guru mata pelajaran
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS teachers (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  subject     VARCHAR(150) NOT NULL,
  -- Sama seperti leadership.photo_url di atas.
  photo_url   VARCHAR(255) NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Struktur organisasi — setiap tingkat (tier) punya daftar nama
-- jabatan/pemegang jabatan. `names` disimpan sebagai JSON array
-- string supaya satu tingkat bisa memuat beberapa kotak sekaligus
-- (mis. tier "Wakil Kepala Sekolah" -> 4 kotak jabatan).
-- (JSON MySQL -> JSONB, padanan terdekat; driver pg mem-parse-nya
-- otomatis menjadi array JS, sama seperti mysql2 sebelumnya.)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS org_tiers (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  level       VARCHAR(150) NOT NULL,
  names       JSONB        NOT NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Galeri (kartu bertajuk, tanpa unggah foto pada versi ini)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS gallery (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(200) NOT NULL,
  icon        VARCHAR(60)  NOT NULL,
  -- Path publik relatif ke foto kegiatan (mis. /uploads/photos/xxx.jpg),
  -- diisi lewat unggahan admin. NULL/kosong berarti belum ada foto —
  -- tampilan publik jatuh kembali ke kartu gradien + ikon.
  photo_url   VARCHAR(255) NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Testimoni
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS testimonials (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  role        VARCHAR(150) NOT NULL,
  quote       TEXT         NOT NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Pesan masuk dari formulir kontak publik
-- (is_read tetap angka 0/1 — bukan BOOLEAN — karena API & frontend
-- admin memakai tipe `0 | 1`. TINYINT(1) MySQL -> SMALLINT + CHECK.)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contact_messages (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  email       VARCHAR(190) NOT NULL,
  message     TEXT         NOT NULL,
  is_read     SMALLINT     NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_contact_messages_is_read CHECK (is_read IN (0, 1))
);

-- =============================================================
-- PPDB — Penerimaan Peserta Didik Baru
-- =============================================================

-- ---------------------------------------------------------------
-- Singleton: pengaturan PPDB (tahun ajaran aktif + buka/tutup pendaftaran).
-- (is_open tetap SMALLINT 0/1 — kode membacanya sebagai `is_open === 1`.)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ppdb_settings (
  id              SMALLINT PRIMARY KEY DEFAULT 1,
  academic_year   VARCHAR(20)  NOT NULL,
  is_open         SMALLINT     NOT NULL DEFAULT 0,
  closed_message  VARCHAR(500) NULL,
  updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_ppdb_settings_singleton CHECK (id = 1),
  CONSTRAINT chk_ppdb_settings_is_open CHECK (is_open IN (0, 1))
);

DROP TRIGGER IF EXISTS trg_ppdb_settings_set_updated_at ON ppdb_settings;
CREATE TRIGGER trg_ppdb_settings_set_updated_at
  BEFORE UPDATE ON ppdb_settings FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Jurusan/peminatan PPDB — dikelola lewat CRUD generik yang sama
-- dengan facilities/testimonials/dst (lihat resources/registry.ts).
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ppdb_majors (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(150) NOT NULL,
  sort_order  INT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------
-- Pendaftaran calon siswa. `nik_encrypted` dienkripsi AES-256-GCM
-- (lihat src/utils/crypto.ts) — TIDAK PERNAH disimpan sebagai teks
-- polos. `nik_hash` adalah HMAC deterministik dari NIK yang sama,
-- dipakai untuk cek duplikat/pencarian tanpa perlu mendekripsi baris.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ppdb_registrations (
  id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Pemilik akun yang mengirim formulir ini (lihat tabel `users`).
  -- NULLable supaya data lama (sebelum fitur login ada) tetap valid.
  user_id                 INT          NULL,
  registration_number     VARCHAR(40)  NOT NULL UNIQUE,
  status                  ppdb_registration_status NOT NULL DEFAULT 'diajukan',

  -- Data calon siswa
  nik_encrypted           VARCHAR(500) NOT NULL,
  nik_hash                CHAR(64)     NOT NULL UNIQUE,
  nisn                    VARCHAR(20)  NOT NULL,
  full_name               VARCHAR(150) NOT NULL,
  birth_place             VARCHAR(150) NOT NULL,
  birth_date              DATE         NOT NULL,
  gender                  ppdb_gender  NOT NULL,
  religion                VARCHAR(50)  NOT NULL,
  phone                   VARCHAR(30)  NOT NULL,
  email                   VARCHAR(190) NOT NULL,

  -- Data alamat
  address                 VARCHAR(400) NOT NULL,
  province                VARCHAR(100) NOT NULL,
  city                    VARCHAR(150) NOT NULL,
  district                VARCHAR(150) NOT NULL,
  village                 VARCHAR(150) NOT NULL,

  -- Data ayah
  father_name             VARCHAR(150) NOT NULL,
  father_job              VARCHAR(150) NOT NULL,
  father_phone            VARCHAR(30)  NOT NULL,

  -- Data ibu
  mother_name             VARCHAR(150) NOT NULL,
  mother_job              VARCHAR(150) NOT NULL,
  mother_phone            VARCHAR(30)  NOT NULL,

  -- Data wali (opsional — hanya diisi bila calon siswa tinggal bersama wali)
  guardian_name           VARCHAR(150) NULL,
  guardian_relationship   VARCHAR(100) NULL,
  guardian_job            VARCHAR(150) NULL,
  guardian_phone          VARCHAR(30)  NULL,

  -- Pilihan pendaftaran
  major_id                INT          NULL,
  academic_year           VARCHAR(20)  NOT NULL,
  previous_school         VARCHAR(200) NOT NULL,

  -- Pernyataan kebenaran data (checkbox wajib dicentang sebelum submit)
  agreement_accepted_at   TIMESTAMPTZ  NOT NULL,

  -- Admin / audit trail
  admin_note              TEXT         NULL,
  verified_by             INT          NULL,
  verified_at             TIMESTAMPTZ  NULL,
  sent_to_dinas_by        INT          NULL,
  sent_to_dinas_at        TIMESTAMPTZ  NULL,
  submitted_ip            VARCHAR(45)  NULL,

  created_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_ppdb_registrations_major
    FOREIGN KEY (major_id) REFERENCES ppdb_majors(id) ON DELETE SET NULL,
  CONSTRAINT fk_ppdb_registrations_verified_by
    FOREIGN KEY (verified_by) REFERENCES admins(id) ON DELETE SET NULL,
  CONSTRAINT fk_ppdb_registrations_sent_by
    FOREIGN KEY (sent_to_dinas_by) REFERENCES admins(id) ON DELETE SET NULL,
  CONSTRAINT fk_ppdb_registrations_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_ppdb_registrations_status  ON ppdb_registrations (status);
CREATE INDEX IF NOT EXISTS idx_ppdb_registrations_created ON ppdb_registrations (created_at);
CREATE INDEX IF NOT EXISTS idx_ppdb_registrations_user    ON ppdb_registrations (user_id);

DROP TRIGGER IF EXISTS trg_ppdb_registrations_set_updated_at ON ppdb_registrations;
CREATE TRIGGER trg_ppdb_registrations_set_updated_at
  BEFORE UPDATE ON ppdb_registrations FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------
-- Dokumen unggahan per pendaftaran (KK, akta, ijazah/SKL, pas foto).
-- Hanya metadata yang disimpan di sini — isi berkas ada di disk, lihat
-- PPDB_UPLOAD_DIR di .env & src/modules/ppdb/ppdb.documents.ts.
-- `stored_filename` adalah nama acak (bukan nama asli) sehingga tidak
-- bisa ditebak dari luar.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ppdb_documents (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id     INT           NOT NULL,
  doc_type            ppdb_doc_type NOT NULL,
  original_filename   VARCHAR(255)  NOT NULL,
  stored_filename     VARCHAR(255)  NOT NULL,
  mime_type           VARCHAR(100)  NOT NULL,
  size_bytes          INT           NOT NULL,
  uploaded_at         TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_ppdb_documents_registration
    FOREIGN KEY (registration_id) REFERENCES ppdb_registrations(id) ON DELETE CASCADE,
  CONSTRAINT uq_ppdb_documents_reg_type UNIQUE (registration_id, doc_type)
);

-- ---------------------------------------------------------------
-- Migrasi tambahan untuk instalasi lama: kolom photo_url ditambahkan
-- belakangan ke tabel achievements (foto siswa berprestasi).
-- Di MySQL ini dicek lewat information_schema + PREPARE/EXECUTE; di
-- PostgreSQL cukup ADD COLUMN IF NOT EXISTS (idempoten & atomik, tanpa
-- SQL dinamis). Pada database baru kolom-kolom di bawah sudah ada di
-- CREATE TABLE di atas, sehingga blok-blok ini tidak berbuat apa-apa.
-- Catatan: PostgreSQL tidak punya "AFTER kolom" — kolom baru selalu
-- ditambahkan di posisi terakhir (tidak berpengaruh, semua query kita
-- menyebut nama kolom secara eksplisit).
-- ---------------------------------------------------------------
ALTER TABLE achievements ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255) NULL;

-- ---------------------------------------------------------------
-- Migrasi tambahan: kolom description & image_url ditambahkan
-- belakangan ke tabel extracurriculars (detail ekskul yang bisa
-- diklik + foto ekskul di halaman publik).
-- ---------------------------------------------------------------
ALTER TABLE extracurriculars ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE extracurriculars ADD COLUMN IF NOT EXISTS image_url VARCHAR(255) NULL;

-- ---------------------------------------------------------------
-- Migrasi tambahan: kolom photo_url ditambahkan belakangan ke
-- tabel leadership & teachers (foto pimpinan sekolah dan guru
-- mata pelajaran di halaman publik, menggantikan avatar inisial
-- bila diisi).
-- ---------------------------------------------------------------
ALTER TABLE leadership ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255) NULL;
ALTER TABLE teachers ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255) NULL;

-- ---------------------------------------------------------------
-- Migrasi tambahan: kolom photo_url ditambahkan belakangan ke
-- tabel gallery (foto kegiatan asli di halaman publik, meng-
-- gantikan kartu gradien + ikon bila diisi).
-- ---------------------------------------------------------------
ALTER TABLE gallery ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255) NULL;

-- ---------------------------------------------------------------
-- Migrasi tambahan: kolom user_id ditambahkan belakangan ke tabel
-- ppdb_registrations (fitur login + verifikasi email sebelum PPDB).
-- Kolom & index memakai IF NOT EXISTS; PostgreSQL tidak punya
-- "ADD CONSTRAINT IF NOT EXISTS", jadi foreign key-nya dicek lewat
-- blok DO ke katalog pg_constraint.
-- ---------------------------------------------------------------
ALTER TABLE ppdb_registrations ADD COLUMN IF NOT EXISTS user_id INT NULL;
CREATE INDEX IF NOT EXISTS idx_ppdb_registrations_user ON ppdb_registrations (user_id);
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'fk_ppdb_registrations_user'
      AND conrelid = 'ppdb_registrations'::regclass
  ) THEN
    ALTER TABLE ppdb_registrations
      ADD CONSTRAINT fk_ppdb_registrations_user
      FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;
  END IF;
END $$;

-- =============================================================
-- Khusus Supabase: aktifkan Row Level Security di semua tabel.
-- Tabel di schema `public` otomatis terjangkau Data API Supabase
-- (REST/GraphQL) lewat anon key yang bersifat publik, dan pada
-- proyek yang masih memberi grant bawaan ke anon/authenticated,
-- tabel yang dibuat lewat SQL TANPA RLS bisa dibaca/ditulis siapa
-- pun — termasuk users.password_hash dan data pribadi pendaftar
-- PPDB. RLS tanpa policy = Data API menolak semuanya. Backend ini
-- TIDAK terpengaruh: ia terhubung langsung sebagai role `postgres`
-- (pemilik tabel) yang melewati RLS. Aman dijalankan berulang, dan
-- tidak berbahaya di PostgreSQL non-Supabase.
-- =============================================================
ALTER TABLE admins             ENABLE ROW LEVEL SECURITY;
ALTER TABLE users              ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_profile     ENABLE ROW LEVEL SECURITY;
ALTER TABLE stats              ENABLE ROW LEVEL SECURITY;
ALTER TABLE history_paragraphs ENABLE ROW LEVEL SECURITY;
ALTER TABLE milestones         ENABLE ROW LEVEL SECURITY;
ALTER TABLE vision_mission     ENABLE ROW LEVEL SECURITY;
ALTER TABLE missions           ENABLE ROW LEVEL SECURITY;
ALTER TABLE facilities         ENABLE ROW LEVEL SECURITY;
ALTER TABLE extracurriculars   ENABLE ROW LEVEL SECURITY;
ALTER TABLE achievements       ENABLE ROW LEVEL SECURITY;
ALTER TABLE leadership         ENABLE ROW LEVEL SECURITY;
ALTER TABLE teachers           ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_tiers          ENABLE ROW LEVEL SECURITY;
ALTER TABLE gallery            ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials       ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages   ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppdb_settings      ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppdb_majors        ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppdb_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppdb_documents     ENABLE ROW LEVEL SECURITY;
